apiVersion: rebellions.ai/v1beta1
kind: RBLNClusterPolicy
metadata:
  labels:
    app.kubernetes.io/name: rbln-npu-operator
  name: rbln-cluster-policy
spec:
  workloadType: container
  # podDefaults applies to all DaemonSet pods managed by this policy.
  # podDefaults:
  #   labels: {}
  #   annotations: {}
  #   tolerations:
  #   - key: node-role.kubernetes.io/control-plane
  #     operator: Exists
  #     effect: NoSchedule
  #   priorityClassName: system-node-critical
  driver:
    upgradePolicy:
      autoUpgrade: false
      maxParallelUpgrades: 1
      waitForCompletion:
        timeoutSeconds: 0
      podDeletion:
        force: false
        timeoutSeconds: 300
      drain:
        enable: false
        force: false
        deleteEmptyDirData: false
        timeoutSeconds: 300
      reboot:
        enable: false
        rebootTimeoutSeconds: 0
        image:
          registry: docker.io
          image: rebellions/rbln-node-reboot
          version: latest
  devicePlugin:
    enabled: true
    registry: docker.io
    image: rebellions/k8s-device-plugin
    version: v0.4.0
    imagePullPolicy: IfNotPresent
  draKubeletPlugin:
    enabled: false
    registry: docker.io
    image: rebellions/k8s-dra-driver-npu
    version: v0.1.2
    imagePullPolicy: IfNotPresent
    driverName: npu.rebellions.ai
    kubeletRegistrarDirectoryPath: /var/lib/kubelet/plugins_registry
    kubeletPluginsDirectoryPath: /var/lib/kubelet/plugins
    healthcheckPort: 51515
  metricsExporter:
    enabled: true
    registry: docker.io
    image: rebellions/rbln-metrics-exporter
    version: v0.2.4
    imagePullPolicy: IfNotPresent
  npuFeatureDiscovery:
    enabled: true
    registry: docker.io
    image: rebellions/rbln-npu-feature-discovery
    version: v0.2.1
    imagePullPolicy: IfNotPresent
  containerToolkit:
    enabled: true
    registry: docker.io
    image: rebellions/rbln-container-toolkit
    version: v0.1.1
    imagePullPolicy: IfNotPresent
  rblnDaemon:
    enabled: false
    registry: repo.rebellions.ai
    image: rebellions/rbln-daemon
    version: "3.0.0"
    imagePullPolicy: IfNotPresent
    hostPort: 50051
    imagePullSecrets:
    - drivercred
  sandboxDevicePlugin:
    enabled: false
    registry: docker.io
    image: rebellions/k8s-device-plugin
    version: v0.3.7
    imagePullPolicy: IfNotPresent
    resourceList:
    - resourceName: ATOM_PT
      resourcePrefix: rebellions.ai
      productCardNames:
      - RBLN-CA12
    - resourceName: ATOM_MAX_PT
      resourcePrefix: rebellions.ai
      productCardNames:
      - RBLN-CA25
    - resourceName: REBEL_PT
      resourcePrefix: rebellions.ai
      productCardNames:
      - RBLN-CR03
  vfioManager:
    enabled: false
    registry: docker.io
    image: rebellions/rbln-vfio-manager
    version: latest
    imagePullPolicy: IfNotPresent
  validator:
    registry: docker.io
    image: rebellions/rbln-npu-operator-validator
    version: latest
    imagePullPolicy: IfNotPresent
