{{- if .Values.driver.enabled }}
apiVersion: rebellions.ai/v1alpha1
kind: RBLNDriver
metadata:
  labels:
    {{- include "rbln-npu-operator.labels" . | nindent 4 }}
  name: rbln-driver
spec:
  registry: {{ .Values.driver.image.registry | quote }}
  image: {{ .Values.driver.image.repository | quote }}
  version: {{ .Values.driver.image.tag | quote }}
  imagePullPolicy: {{ .Values.driver.image.pullPolicy | quote }}
  {{- with .Values.driver.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.driver.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.driver.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.driver.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.driver.priorityClassName }}
  priorityClassName: {{ .Values.driver.priorityClassName | quote }}
  {{- end }}
  {{- with .Values.driver.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.driver.env }}
  env:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.driver.manager }}
  manager:
    {{- if .image }}
    registry: {{ .image.registry | quote }}
    image: {{ .image.repository | quote }}
    version: {{ .image.tag | quote }}
    imagePullPolicy: {{ .image.pullPolicy | quote }}
    {{- end }}
    {{- with .imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
