{{- if and .Values.operator.metrics .Values.operator.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "rbln-npu-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: rbln-operator-controller-manager-metrics-service
spec:
  ports:
    - name: https
      port: {{ .Values.operator.metrics.port | default 8443 }}
      protocol: TCP
      targetPort: https
  selector:
    {{- include "rbln-npu-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
