//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainSpec) DeepCopyInto(out *DrainSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainSpec.
func (in *DrainSpec) DeepCopy() *DrainSpec {
	if in == nil {
		return nil
	}
	out := new(DrainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverSpec) DeepCopyInto(out *DriverSpec) {
	*out = *in
	if in.UpgradePolicy != nil {
		in, out := &in.UpgradePolicy, &out.UpgradePolicy
		*out = new(DriverUpgradePolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverSpec.
func (in *DriverSpec) DeepCopy() *DriverSpec {
	if in == nil {
		return nil
	}
	out := new(DriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverUpgradePolicySpec) DeepCopyInto(out *DriverUpgradePolicySpec) {
	*out = *in
	if in.PodDeletion != nil {
		in, out := &in.PodDeletion, &out.PodDeletion
		*out = new(PodDeletionSpec)
		**out = **in
	}
	if in.WaitForCompletion != nil {
		in, out := &in.WaitForCompletion, &out.WaitForCompletion
		*out = new(WaitForCompletionSpec)
		**out = **in
	}
	if in.DrainSpec != nil {
		in, out := &in.DrainSpec, &out.DrainSpec
		*out = new(DrainSpec)
		**out = **in
	}
	if in.Reboot != nil {
		in, out := &in.Reboot, &out.Reboot
		*out = new(RebootSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverUpgradePolicySpec.
func (in *DriverUpgradePolicySpec) DeepCopy() *DriverUpgradePolicySpec {
	if in == nil {
		return nil
	}
	out := new(DriverUpgradePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverValidatorSpec) DeepCopyInto(out *DriverValidatorSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverValidatorSpec.
func (in *DriverValidatorSpec) DeepCopy() *DriverValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(DriverValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDefaultsSpec) DeepCopyInto(out *PodDefaultsSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDefaultsSpec.
func (in *PodDefaultsSpec) DeepCopy() *PodDefaultsSpec {
	if in == nil {
		return nil
	}
	out := new(PodDefaultsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDeletionSpec) DeepCopyInto(out *PodDeletionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDeletionSpec.
func (in *PodDeletionSpec) DeepCopy() *PodDeletionSpec {
	if in == nil {
		return nil
	}
	out := new(PodDeletionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSpec) DeepCopyInto(out *PodSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSpec.
func (in *PodSpec) DeepCopy() *PodSpec {
	if in == nil {
		return nil
	}
	out := new(PodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNClusterPolicy) DeepCopyInto(out *RBLNClusterPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNClusterPolicy.
func (in *RBLNClusterPolicy) DeepCopy() *RBLNClusterPolicy {
	if in == nil {
		return nil
	}
	out := new(RBLNClusterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RBLNClusterPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNClusterPolicyList) DeepCopyInto(out *RBLNClusterPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RBLNClusterPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNClusterPolicyList.
func (in *RBLNClusterPolicyList) DeepCopy() *RBLNClusterPolicyList {
	if in == nil {
		return nil
	}
	out := new(RBLNClusterPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RBLNClusterPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNClusterPolicySpec) DeepCopyInto(out *RBLNClusterPolicySpec) {
	*out = *in
	if in.PodDefaults != nil {
		in, out := &in.PodDefaults, &out.PodDefaults
		*out = new(PodDefaultsSpec)
		(*in).DeepCopyInto(*out)
	}
	in.VFIOManager.DeepCopyInto(&out.VFIOManager)
	in.SandboxDevicePlugin.DeepCopyInto(&out.SandboxDevicePlugin)
	in.DevicePlugin.DeepCopyInto(&out.DevicePlugin)
	in.DRAKubeletPlugin.DeepCopyInto(&out.DRAKubeletPlugin)
	in.MetricsExporter.DeepCopyInto(&out.MetricsExporter)
	in.NPUFeatureDiscovery.DeepCopyInto(&out.NPUFeatureDiscovery)
	in.ContainerToolkit.DeepCopyInto(&out.ContainerToolkit)
	in.Validator.DeepCopyInto(&out.Validator)
	in.Driver.DeepCopyInto(&out.Driver)
	in.RDS.DeepCopyInto(&out.RDS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNClusterPolicySpec.
func (in *RBLNClusterPolicySpec) DeepCopy() *RBLNClusterPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RBLNClusterPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNClusterPolicyStatus) DeepCopyInto(out *RBLNClusterPolicyStatus) {
	*out = *in
	if in.Workloads != nil {
		in, out := &in.Workloads, &out.Workloads
		*out = make([]RBLNWorkloadStatus, len(*in))
		copy(*out, *in)
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]RBLNComponentStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNClusterPolicyStatus.
func (in *RBLNClusterPolicyStatus) DeepCopy() *RBLNClusterPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RBLNClusterPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNComponentStatus) DeepCopyInto(out *RBLNComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNComponentStatus.
func (in *RBLNComponentStatus) DeepCopy() *RBLNComponentStatus {
	if in == nil {
		return nil
	}
	out := new(RBLNComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNContainerToolkitSpec) DeepCopyInto(out *RBLNContainerToolkitSpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
	if in.RefreshInterval != nil {
		in, out := &in.RefreshInterval, &out.RefreshInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNContainerToolkitSpec.
func (in *RBLNContainerToolkitSpec) DeepCopy() *RBLNContainerToolkitSpec {
	if in == nil {
		return nil
	}
	out := new(RBLNContainerToolkitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNDRAKubeletPluginSpec) DeepCopyInto(out *RBLNDRAKubeletPluginSpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNDRAKubeletPluginSpec.
func (in *RBLNDRAKubeletPluginSpec) DeepCopy() *RBLNDRAKubeletPluginSpec {
	if in == nil {
		return nil
	}
	out := new(RBLNDRAKubeletPluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNDevicePluginSpec) DeepCopyInto(out *RBLNDevicePluginSpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNDevicePluginSpec.
func (in *RBLNDevicePluginSpec) DeepCopy() *RBLNDevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(RBLNDevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNMetricsExporterSpec) DeepCopyInto(out *RBLNMetricsExporterSpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNMetricsExporterSpec.
func (in *RBLNMetricsExporterSpec) DeepCopy() *RBLNMetricsExporterSpec {
	if in == nil {
		return nil
	}
	out := new(RBLNMetricsExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNNPUFeatureDiscoverySpec) DeepCopyInto(out *RBLNNPUFeatureDiscoverySpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNNPUFeatureDiscoverySpec.
func (in *RBLNNPUFeatureDiscoverySpec) DeepCopy() *RBLNNPUFeatureDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(RBLNNPUFeatureDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNRDSDeviceSelection) DeepCopyInto(out *RBLNRDSDeviceSelection) {
	*out = *in
	if in.TargetBDFs != nil {
		in, out := &in.TargetBDFs, &out.TargetBDFs
		*out = make([]PCIDeviceAddress, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNRDSDeviceSelection.
func (in *RBLNRDSDeviceSelection) DeepCopy() *RBLNRDSDeviceSelection {
	if in == nil {
		return nil
	}
	out := new(RBLNRDSDeviceSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNRDSSpec) DeepCopyInto(out *RBLNRDSSpec) {
	*out = *in
	if in.DeviceSelection != nil {
		in, out := &in.DeviceSelection, &out.DeviceSelection
		*out = make([]RBLNRDSDeviceSelection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNRDSSpec.
func (in *RBLNRDSSpec) DeepCopy() *RBLNRDSSpec {
	if in == nil {
		return nil
	}
	out := new(RBLNRDSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNSandboxDevicePluginSpec) DeepCopyInto(out *RBLNSandboxDevicePluginSpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNSandboxDevicePluginSpec.
func (in *RBLNSandboxDevicePluginSpec) DeepCopy() *RBLNSandboxDevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(RBLNSandboxDevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNVFIOManagerSpec) DeepCopyInto(out *RBLNVFIOManagerSpec) {
	*out = *in
	in.DriverManager.DeepCopyInto(&out.DriverManager)
	in.PodSpec.DeepCopyInto(&out.PodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNVFIOManagerSpec.
func (in *RBLNVFIOManagerSpec) DeepCopy() *RBLNVFIOManagerSpec {
	if in == nil {
		return nil
	}
	out := new(RBLNVFIOManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBLNWorkloadStatus) DeepCopyInto(out *RBLNWorkloadStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBLNWorkloadStatus.
func (in *RBLNWorkloadStatus) DeepCopy() *RBLNWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(RBLNWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebootImageSpec) DeepCopyInto(out *RebootImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebootImageSpec.
func (in *RebootImageSpec) DeepCopy() *RebootImageSpec {
	if in == nil {
		return nil
	}
	out := new(RebootImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebootSpec) DeepCopyInto(out *RebootSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(RebootImageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebootSpec.
func (in *RebootSpec) DeepCopy() *RebootSpec {
	if in == nil {
		return nil
	}
	out := new(RebootSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolkitValidatorSpec) DeepCopyInto(out *ToolkitValidatorSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolkitValidatorSpec.
func (in *ToolkitValidatorSpec) DeepCopy() *ToolkitValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(ToolkitValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VFIODriverManagerSpec) DeepCopyInto(out *VFIODriverManagerSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VFIODriverManagerSpec.
func (in *VFIODriverManagerSpec) DeepCopy() *VFIODriverManagerSpec {
	if in == nil {
		return nil
	}
	out := new(VFIODriverManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatorSpec) DeepCopyInto(out *ValidatorSpec) {
	*out = *in
	in.Toolkit.DeepCopyInto(&out.Toolkit)
	in.Driver.DeepCopyInto(&out.Driver)
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatorSpec.
func (in *ValidatorSpec) DeepCopy() *ValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(ValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForCompletionSpec) DeepCopyInto(out *WaitForCompletionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForCompletionSpec.
func (in *WaitForCompletionSpec) DeepCopy() *WaitForCompletionSpec {
	if in == nil {
		return nil
	}
	out := new(WaitForCompletionSpec)
	in.DeepCopyInto(out)
	return out
}
