name: Golang Code Checks

on:
  workflow_call:

jobs:
  # Synchronize code lint, formatting, manifests and bundle.
  code-check:
    name: golang code checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: ./.github/actions/setup-go
        name: Setup Go
      - name: Run code-check
        run: make code-check
