name: Golang Code Tests

on:
  workflow_call:

jobs:
  go-tests:
    name: golang unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: ./.github/actions/setup-go
        name: Setup Go
      - name: Run unit tests
        run: make unit-tests
