name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  manifests-check:
    uses: ./.github/workflows/manifests-check.yaml
  code-check:
    uses: ./.github/workflows/go-checks.yaml
  go-tests:
    uses: ./.github/workflows/go-tests.yaml
  go-build:
    uses: ./.github/workflows/go-build.yaml
  image-build-amd64:
    needs: [manifests-check, code-check, go-tests, go-build]
    uses: ./.github/workflows/image-build.yaml
    with:
      push-on-build: 'true'
      image-tag: latest
      platform: linux/amd64
      runner: ubuntu-latest
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  image-build-arm64:
    needs: [manifests-check, code-check, go-tests, go-build]
    uses: ./.github/workflows/image-build.yaml
    with:
      push-on-build: 'true'
      image-tag: latest
      platform: linux/arm64
      runner: ubuntu-22.04-rbln-arm
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  image-manifest:
    needs: [image-build-amd64, image-build-arm64]
    uses: ./.github/workflows/image-manifest.yaml
    with:
      image-tag: latest
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
